-- =========================================================
-- StreamPulse Project Setup
-- Real-Time Media Analytics + TimescaleDB Diagnostics
-- =========================================================

-- Make sure TimescaleDB is enabled
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- Clean up old objects if you re-run the project
DROP MATERIALIZED VIEW IF EXISTS media_events_5min_summary CASCADE;
DROP MATERIALIZED VIEW IF EXISTS api_metrics_5min_summary CASCADE;

DROP TABLE IF EXISTS media_events CASCADE;
DROP TABLE IF EXISTS api_metrics CASCADE;
DROP TABLE IF EXISTS content_catalog CASCADE;

-- =========================================================
-- 1. Content catalog table
-- This is a normal dimension table.
-- It stores metadata about movies, shows, songs, and live events.
-- =========================================================

CREATE TABLE content_catalog (
    content_id      INTEGER PRIMARY KEY,
    title           TEXT NOT NULL,
    content_type    TEXT NOT NULL,
    genre           TEXT NOT NULL,
    release_date    DATE NOT NULL
);

-- =========================================================
-- 2. Media events table
-- This stores user actions like play, pause, skip, rewatch, buffering.
-- This will become a TimescaleDB hypertable.
-- =========================================================

CREATE TABLE media_events (
    event_time      TIMESTAMPTZ NOT NULL,
    event_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id         INTEGER NOT NULL,
    content_id      INTEGER NOT NULL REFERENCES content_catalog(content_id),
    event_type      TEXT NOT NULL,
    device_type     TEXT NOT NULL,
    region          TEXT NOT NULL,
    watch_seconds   INTEGER NOT NULL DEFAULT 0,
    bitrate_kbps    INTEGER,
    buffer_ms       INTEGER,
    app_version     TEXT,
    PRIMARY KEY (event_time, event_id)
);

-- Convert media_events into a hypertable
SELECT create_hypertable(
    'media_events',
    by_range('event_time'),
    if_not_exists => TRUE
);

-- =========================================================
-- 3. API metrics table
-- This stores backend/API performance metrics.
-- Example: latency, status code, request count, CPU usage.
-- This will also become a TimescaleDB hypertable.
-- =========================================================

CREATE TABLE api_metrics (
    metric_time     TIMESTAMPTZ NOT NULL,
    service_name    TEXT NOT NULL,
    endpoint        TEXT NOT NULL,
    region          TEXT NOT NULL,
    status_code     INTEGER NOT NULL,
    response_ms     INTEGER NOT NULL,
    request_count   INTEGER NOT NULL,
    cpu_pct         NUMERIC(5,2) NOT NULL
);

-- Convert api_metrics into a hypertable
SELECT create_hypertable(
    'api_metrics',
    by_range('metric_time'),
    if_not_exists => TRUE
);